// Locals Management Actions
const FETCH_CITIES = 100
const GET_CITY = 101
const UPDATE_VIEW = 102
const UPDATE_ITINERARIES = 103
const UPDATE_IT_ACTIVITIES = 104
const UPDATE_IT_COMMENTS = 105
// USER MANAGEMENT Actions
const CHECK_USER = 200
const UPDATE_USER = 201

export { 
    FETCH_CITIES, 
    GET_CITY, 
    UPDATE_VIEW, 
    UPDATE_ITINERARIES,
    UPDATE_IT_ACTIVITIES,
    UPDATE_IT_COMMENTS,
    CHECK_USER, 
    UPDATE_USER
};